import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { ShoppingBag } from "lucide-react";
import { MobilePage, PageTabs, Stepper } from "../components/MobilePage";
import lager from "../assets/amber-lager.jpg";
import dunkel from "../assets/dunkel-beer.jpg";
export const Route = createFileRoute("/order/")({ head:()=>({meta:[{title:"桌边点单｜客满酒馆"},{name:"description",content:"客满酒馆酒水与小食点单。"},{property:"og:title",content:"桌边点单｜客满酒馆"},{property:"og:description",content:"精选德式精酿与佐酒小食。"},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}), component: Order });
const products=[{id:1,name:"慕尼黑琥珀拉格",meta:"500ml · 麦香清爽",price:32,img:lager},{id:2,name:"巴伐利亚黑啤",meta:"500ml · 焦香醇厚",price:38,img:dunkel},{id:3,name:"德式脆皮烤肠",meta:"2根 · 黄芥末酱",price:42,img:lager},{id:4,name:"巴伐利亚椒盐结",meta:"现烤 · 奶油蘸酱",price:26,img:dunkel}];
function Order(){const [tab,setTab]=useState("精酿啤酒");const [qty,setQty]=useState<Record<number,number>>({});const count=Object.values(qty).reduce((a,b)=>a+b,0);const total=products.reduce((sum,p)=>sum+p.price*(qty[p.id]||0),0);return <MobilePage title="桌边点单" eyebrow="ORDER"><div className="rounded-md border border-primary/30 bg-primary-soft p-3 text-xs text-primary">环球港店 · 请先扫描桌台二维码</div><div className="mt-4"><PageTabs items={["精酿啤酒","佐酒小食","招牌特调"]} value={tab} onChange={setTab}/></div><div className="mt-4 grid grid-cols-2 gap-3">{products.map(p=><article key={p.id} className="overflow-hidden rounded-md border border-line bg-panel"><img src={p.img} alt={p.name} className="aspect-[4/3] w-full object-cover"/><div className="p-3"><h2 className="text-sm font-semibold">{p.name}</h2><p className="mt-1 text-[11px] text-muted-foreground">{p.meta}</p><div className="mt-3 flex items-center justify-between"><span className="font-display text-lg text-primary">¥{p.price}</span><Stepper value={qty[p.id]||0} onChange={v=>setQty({...qty,[p.id]:v})}/></div></div></article>)}</div>{count>0&&<Link to="/order/checkout" search={{count,total}} className="fixed bottom-20 left-1/2 z-20 flex w-[calc(100%-32px)] max-w-[398px] -translate-x-1/2 items-center justify-between rounded-md bg-primary px-5 py-4 text-primary-foreground shadow-panel"><span className="flex items-center gap-2 text-sm"><ShoppingBag className="size-5"/>{count} 件 · ¥{total}</span><b className="text-sm">去结算</b></Link>}</MobilePage>}
