import { Link } from "@tanstack/react-router";
import { ArrowLeft, Check, CircleUserRound, House, Trophy, UtensilsCrossed, X } from "lucide-react";
import type { ReactNode } from "react";
import { AppButton } from "./AppButton";

export function MobilePage({ title, eyebrow, children, back = "/", nav = true, action }: { title: string; eyebrow?: string; children: ReactNode; back?: string; nav?: boolean; action?: ReactNode }) {
  return <main className="min-h-screen bg-page text-foreground font-sans"><div className="mx-auto min-h-screen w-full max-w-[430px] bg-background pb-28 shadow-phone"><header className="sticky top-0 z-20 flex min-h-16 items-center justify-between border-b border-line bg-nav px-4 backdrop-blur-xl"><Link to={back} aria-label="返回" className="grid size-10 place-items-center rounded-full text-foreground"><ArrowLeft className="size-5" /></Link><div className="text-center">{eyebrow && <p className="section-kicker">{eyebrow}</p>}<h1 className="font-display text-lg font-semibold">{title}</h1></div><div className="flex size-10 items-center justify-end">{action}</div></header><div className="px-4 py-5">{children}</div>{nav && <BottomNav />}</div></main>;
}

export function BottomNav() { return <nav className="fixed bottom-0 left-1/2 z-30 grid w-full max-w-[430px] -translate-x-1/2 grid-cols-4 border-t border-line bg-nav px-4 pb-[max(12px,env(safe-area-inset-bottom))] pt-3 backdrop-blur-xl"><Nav to="/" icon={House} label="首页" /><Nav to="/order" icon={UtensilsCrossed} label="点单" /><Nav to="/events" icon={Trophy} label="赛事" /><Nav to="/member" icon={CircleUserRound} label="我的" /></nav>; }
function Nav({ to, icon: Icon, label }: { to: "/" | "/order" | "/events" | "/member"; icon: typeof House; label: string }) { return <Link to={to} activeOptions={{ exact: to === "/" }} activeProps={{ className: "text-primary" }} inactiveProps={{ className: "text-muted-foreground" }} className="flex flex-col items-center gap-1"><Icon className="size-5" /><span className="text-[11px] font-medium">{label}</span></Link>; }

export function PageTabs({ items, value, onChange }: { items: string[]; value: string; onChange: (value: string) => void }) { return <div className="flex gap-1 rounded-md bg-muted p-1">{items.map((item) => <AppButton key={item} onClick={() => onChange(item)} className={`flex-1 rounded-sm py-2 text-xs font-semibold ${value === item ? "bg-primary text-primary-foreground" : "bg-transparent text-muted-foreground"}`}>{item}</AppButton>)}</div>; }
export function SelectTile({ title, note, active, onClick }: { title: string; note?: string; active?: boolean; onClick: () => void }) { return <AppButton onClick={onClick} className={`w-full rounded-md border p-4 text-left ${active ? "border-primary bg-primary-soft" : "border-line bg-panel"}`}><span className="flex items-center justify-between"><span className="text-sm font-semibold">{title}</span>{active && <Check className="size-4 text-primary" />}</span>{note && <span className="mt-1 block text-xs text-muted-foreground">{note}</span>}</AppButton>; }
export function Stepper({ value, onChange }: { value: number; onChange: (value: number) => void }) { return <div className="flex items-center gap-3"><AppButton aria-label="减少" onClick={() => onChange(Math.max(0, value - 1))} className="grid size-8 place-items-center rounded-full border border-line bg-muted">−</AppButton><span className="w-5 text-center text-sm font-semibold">{value}</span><AppButton aria-label="增加" onClick={() => onChange(value + 1)} className="grid size-8 place-items-center rounded-full bg-primary text-primary-foreground">+</AppButton></div>; }
export function PrimaryAction({ children, onClick, disabled = false }: { children: ReactNode; onClick: () => void; disabled?: boolean }) { return <AppButton disabled={disabled} onClick={onClick} className="w-full rounded-sm bg-primary py-3.5 text-sm font-semibold text-primary-foreground disabled:bg-muted disabled:text-muted-foreground">{children}</AppButton>; }
export function SuccessOverlay({ title, note, onClose }: { title: string; note: string; onClose: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-overlay px-6"><div className="relative w-full max-w-sm rounded-md border border-primary/30 bg-panel p-6 text-center shadow-sheet"><AppButton onClick={onClose} aria-label="关闭" className="absolute right-3 top-3 grid size-8 place-items-center rounded-full bg-muted"><X className="size-4" /></AppButton><div className="mx-auto grid size-14 place-items-center rounded-full bg-open"><Check className="size-7 text-open-foreground" /></div><h2 className="mt-4 font-display text-xl font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{note}</p><AppButton onClick={onClose} className="mt-5 w-full rounded-sm bg-primary py-3 text-sm font-semibold text-primary-foreground">完成</AppButton></div></div>; }
