/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as EventsRouteImport } from './routes/events'
import { Route as MemberRouteImport } from './routes/member'
import { Route as OrderRouteImport } from './routes/order'
import { Route as PresaleRouteImport } from './routes/presale'
import { Route as RechargeRouteImport } from './routes/recharge'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as OrderIndexRouteImport } from './routes/order.index'
import { Route as OrderCheckoutRouteImport } from './routes/order.checkout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const PresaleRoute = PresaleRouteImport.update({
  id: '/presale',
  path: '/presale',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeRoute = RechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIndexRoute = OrderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrderRoute,
} as any)
const OrderCheckoutRoute = OrderCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => OrderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/coupons': typeof CouponsRoute
  '/events': typeof EventsRoute
  '/member': typeof MemberRoute
  '/order': typeof OrderRouteWithChildren
  '/presale': typeof PresaleRoute
  '/recharge': typeof RechargeRoute
  '/storage': typeof StorageRoute
  '/order/checkout': typeof OrderCheckoutRoute
  '/order/': typeof OrderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/coupons': typeof CouponsRoute
  '/events': typeof EventsRoute
  '/member': typeof MemberRoute
  '/presale': typeof PresaleRoute
  '/recharge': typeof RechargeRoute
  '/storage': typeof StorageRoute
  '/order/checkout': typeof OrderCheckoutRoute
  '/order': typeof OrderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/coupons': typeof CouponsRoute
  '/events': typeof EventsRoute
  '/member': typeof MemberRoute
  '/order': typeof OrderRouteWithChildren
  '/presale': typeof PresaleRoute
  '/recharge': typeof RechargeRoute
  '/storage': typeof StorageRoute
  '/order/checkout': typeof OrderCheckoutRoute
  '/order/': typeof OrderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/coupons'
    | '/events'
    | '/member'
    | '/order'
    | '/presale'
    | '/recharge'
    | '/storage'
    | '/order/checkout'
    | '/order/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/coupons'
    | '/events'
    | '/member'
    | '/presale'
    | '/recharge'
    | '/storage'
    | '/order/checkout'
    | '/order'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/coupons'
    | '/events'
    | '/member'
    | '/order'
    | '/presale'
    | '/recharge'
    | '/storage'
    | '/order/checkout'
    | '/order/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  CouponsRoute: typeof CouponsRoute
  EventsRoute: typeof EventsRoute
  MemberRoute: typeof MemberRoute
  OrderRoute: typeof OrderRouteWithChildren
  PresaleRoute: typeof PresaleRoute
  RechargeRoute: typeof RechargeRoute
  StorageRoute: typeof StorageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presale': {
      id: '/presale'
      path: '/presale'
      fullPath: '/presale'
      preLoaderRoute: typeof PresaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge': {
      id: '/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof RechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/': {
      id: '/order/'
      path: '/'
      fullPath: '/order/'
      preLoaderRoute: typeof OrderIndexRouteImport
      parentRoute: typeof OrderRoute
    }
    '/order/checkout': {
      id: '/order/checkout'
      path: '/checkout'
      fullPath: '/order/checkout'
      preLoaderRoute: typeof OrderCheckoutRouteImport
      parentRoute: typeof OrderRoute
    }
  }
}

interface OrderRouteChildren {
  OrderCheckoutRoute: typeof OrderCheckoutRoute
  OrderIndexRoute: typeof OrderIndexRoute
}

const OrderRouteChildren: OrderRouteChildren = {
  OrderCheckoutRoute: OrderCheckoutRoute,
  OrderIndexRoute: OrderIndexRoute,
}

const OrderRouteWithChildren = OrderRoute._addFileChildren(OrderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  CouponsRoute: CouponsRoute,
  EventsRoute: EventsRoute,
  MemberRoute: MemberRoute,
  OrderRoute: OrderRouteWithChildren,
  PresaleRoute: PresaleRoute,
  RechargeRoute: RechargeRoute,
  StorageRoute: StorageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
